---
abstract: 'Format an Array as an Array of String aligned in columns.'
author:
  - 'Rocky Bernstein <rocky@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-Array-Columnize
requires:
  ExtUtils::PkgConfig: 1.03
  Test::More: 0
  version: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: v0.3.5
